name: Build & Test & Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    # Use the official Playwright image (includes Node.js, browsers, drivers)
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.53.1-jammy
      # (Optionally tweak shared-memory or add capabilities if you hit chromium sandbox issues)
      options: --shm-size 1gb

    steps:
      # 1. Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Node.js environment (already comes with Node in the Playwright image)
      - name: Setup Node.js cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 3. Install dependencies (including Playwright client)
      - name: Install dependencies
        run: npm ci

      # 4. Run tests (browsers are pre-installed in this container)
      - name: Run tests
        run: npm test
      # 6. Build the production bundle
      - name: Build game
        run: npm run build

      # 7. Install rsync so the deploy action can copy files
      - name: Install rsync
        run: |
          apt-get update
          apt-get install -y rsync
      # 8. Deploy to GitHub Pages (only on push to main)
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
          clean: true